# Generated by Django 5.2.8 on 2025-11-28 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Excel файл')),
                ('status', models.CharField(choices=[('pending', '⏳ В обработке'), ('success', '✅ Успешно'), ('error', '❌ Ошибка')], default='pending', max_length=20)),
                ('imported_count', models.IntegerField(default=0, verbose_name='Импортировано товаров')),
                ('error_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('errors', models.TextField(blank=True, verbose_name='Ошибки импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
